name: Deploy to Staging

on:
  push:
    branches: [development]
  workflow_dispatch: # Allow manual triggering

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://staging.difnotless.com
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Set up environment variables
        run: |
          echo "SHOPIFY_ACCESS_TOKEN=${{ secrets.SHOPIFY_ACCESS_TOKEN }}" >> .env.local
          echo "MYSHOPIFY_DOMAIN=${{ secrets.MYSHOPIFY_DOMAIN }}" >> .env.local
          echo "AIRTABLE_API_KEY=${{ secrets.AIRTABLE_API_KEY }}" >> .env.local
          echo "SANITY_PROJECT_ID=${{ secrets.SANITY_PROJECT_ID }}" >> .env.local
      - name: Build for staging
        run: npm run build
      - name: Deploy to staging
        run: |
          # Deploy command for Vercel
          npx vercel --token ${{ secrets.VERCEL_TOKEN }} --prod
      - name: Notify deployment status
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "Deployment to staging successful"
            # Add notification commands here (e.g., Slack webhook)
          else
            echo "Deployment to staging failed"
            # Add failure notification commands here
          fi
